#! /bin/bash -vx

TOMCAT=~/apps/apache-tomcat-7.0.42

git pull origin master
rm -r ../build
cd ..
ant
cd scripts

$TOMCAT/bin/shutdown.sh
sleep 4
rm -r $TOMCAT/webapps/ROOT*
rm -r $TOMCAT/logs/*
cp ../build/latest/q.war $TOMCAT/webapps/ROOT.war

$TOMCAT/bin/startup.sh
