#! /bin/bash -vx

TOMCAT=/var/lib/tomcat7

git pull origin master
rm -r ../build
cd ..
ant
cd scripts

service tomcat7 stop
sleep 4
rm -r $TOMCAT/webapps/ROOT*
rm -r $TOMCAT/logs/*
cp ../build/latest/q.war $TOMCAT/webapps/ROOT.war

service tomcat7 start
